language: node_js

cache: yarn

node_js:
  - 'stable'
  - '6'
  - '8'

sudo: false

script:
  - yarn test

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key:
      secure: ''
    on:
      tags: true
      node: '8'
    skip_cleanup: true
